//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS_CIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complaint()
        {
            this.ComplaintEmployeeAssignments = new HashSet<ComplaintEmployeeAssignment>();
        }
    
        public int ComplaintID { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> MilestoneID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<int> Severity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintEmployeeAssignment> ComplaintEmployeeAssignments { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Milestone Milestone { get; set; }
        public virtual Project Project { get; set; }
        public virtual Deliverable Deliverable { get; set; }
    }
}
