//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS_CIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePerformance
    {
        public int EmployeePerformanceID { get; set; }
        public string EmployeeID { get; set; }
        public string PerformanceGrade { get; set; }
        public string EfficiencyGrade { get; set; }
        public string SkillDomain { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
