//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS_CIO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class FinanceTransaction
    {
        public int FinanceTransactionID { get; set; }
        public string TransactionType { get; set; }
        public string IdentificationDocumentNumber { get; set; }
        public string IdentificationDocumentType { get; set; }
        public decimal Amount { get; set; }
        public string SenderIdentification { get; set; }
        public string ReceiverIdentification { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> ProjectFinanceID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProjectFinance ProjectFinance { get; set; }
        public virtual Project Project { get; set; }
    }
}
