//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS_CIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health
    {
        public int HealthID { get; set; }
        public string PersonID { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<double> BMI { get; set; }
        public Nullable<int> EyeSight { get; set; }
        public string Allergy { get; set; }
        public string Disease { get; set; }
        public string OtherHealthIssue { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
