//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS_CIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNNData
    {
        public string CNIC { get; set; }
        public Nullable<int> Age { get; set; }
        public string JobDescription { get; set; }
        public string City { get; set; }
        public string DegreeName { get; set; }
        public string DegreeType { get; set; }
        public string BoardUniversity { get; set; }
        public Nullable<double> CGPA_Percentage { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<double> Distance { get; set; }
        public string Gender { get; set; }
        public string CertificationName { get; set; }
        public string CertificationGrade { get; set; }
        public Nullable<double> BMI { get; set; }
        public Nullable<int> Eyesight { get; set; }
        public string Allergy { get; set; }
        public string Disease { get; set; }
        public string Skill { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
