//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS_CIO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DSS_CIO2Entities : DbContext
    {
        public DSS_CIO2Entities()
            : base("name=DSS_CIO2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certification> Certifications { get; set; }
        public virtual DbSet<ComplaintEmployeeAssignment> ComplaintEmployeeAssignments { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerProjectMapping> CustomerProjectMappings { get; set; }
        public virtual DbSet<Deliverable> Deliverables { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<EmployeePerformance> EmployeePerformances { get; set; }
        public virtual DbSet<EmployeeResourceAssignment> EmployeeResourceAssignments { get; set; }
        public virtual DbSet<EmployeeTaskAssignment> EmployeeTaskAssignments { get; set; }
        public virtual DbSet<FinanceTransaction> FinanceTransactions { get; set; }
        public virtual DbSet<Health> Healths { get; set; }
        public virtual DbSet<InanimateResource> InanimateResources { get; set; }
        public virtual DbSet<JobDescription> JobDescriptions { get; set; }
        public virtual DbSet<KNNData> KNNDatas { get; set; }
        public virtual DbSet<Milestone> Milestones { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonRelationshipAssignment> PersonRelationshipAssignments { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectEmployeeAssignment> ProjectEmployeeAssignments { get; set; }
        public virtual DbSet<ProjectFinance> ProjectFinances { get; set; }
        public virtual DbSet<ProjectResourceAssignment> ProjectResourceAssignments { get; set; }
        public virtual DbSet<SkillPrediction> SkillPredictions { get; set; }
    
        [DbFunction("DSS_CIO2Entities", "func_Split")]
        public virtual IQueryable<func_Split_Result> func_Split(string delimitedString, string delimitedString2, string delimitedString3, string delimiter)
        {
            var delimitedStringParameter = delimitedString != null ?
                new ObjectParameter("DelimitedString", delimitedString) :
                new ObjectParameter("DelimitedString", typeof(string));
    
            var delimitedString2Parameter = delimitedString2 != null ?
                new ObjectParameter("DelimitedString2", delimitedString2) :
                new ObjectParameter("DelimitedString2", typeof(string));
    
            var delimitedString3Parameter = delimitedString3 != null ?
                new ObjectParameter("DelimitedString3", delimitedString3) :
                new ObjectParameter("DelimitedString3", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<func_Split_Result>("[DSS_CIO2Entities].[func_Split](@DelimitedString, @DelimitedString2, @DelimitedString3, @Delimiter)", delimitedStringParameter, delimitedString2Parameter, delimitedString3Parameter, delimiterParameter);
        }
    
        public virtual int KNNALGORITHM(string cNIC, ObjectParameter salary1, ObjectParameter salary2, ObjectParameter salary3)
        {
            var cNICParameter = cNIC != null ?
                new ObjectParameter("CNIC", cNIC) :
                new ObjectParameter("CNIC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KNNALGORITHM", cNICParameter, salary1, salary2, salary3);
        }
    
        public virtual int KNNALGORITHMSKILL(string cNIC)
        {
            var cNICParameter = cNIC != null ?
                new ObjectParameter("CNIC", cNIC) :
                new ObjectParameter("CNIC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KNNALGORITHMSKILL", cNICParameter);
        }
    }
}
