//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS_CIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRelationshipAssignment
    {
        public int RelationshipID { get; set; }
        public string Person1ID { get; set; }
        public string Person2ID { get; set; }
        public string Relationship2 { get; set; }
        public string Relationship { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
